/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package adminInternalFrame;
import Database.dbcon;
import activity.MainActivity;
import activity.signup;
import java.awt.Color;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;

/**
 *
 * @author User
 */
public class Addproduct extends javax.swing.JInternalFrame {

  
    public Addproduct() {
        initComponents();
         productidtxt.setBackground(new Color(0,0,0,1));
         productnametxt.setBackground(new Color(0,0,0,1));
         productcategorytxt.setBackground(new Color(0,0,0,1));
         productquantitytxt.setBackground(new Color(0,0,0,1));
         productshorttxt.setBackground(new Color(0,0,0,1));
         productpricetxt.setBackground(new Color(0,0,0,1));
         productimgtxt.setBackground(new Color(0,0,0,1));
          img1txt.setBackground(new Color(0,0,0,1));
          img2txt.setBackground(new Color(0,0,0,1));
          img3txt.setBackground(new Color(0,0,0,1));
          product_statustxt.setBackground(new Color(0,0,0,1));
         
         
        
           setBorder(BorderFactory.createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI UI = (BasicInternalFrameUI) getUI();
        UI.setNorthPane(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        productpricetxt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        productidtxt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        productnametxt = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        productcategorytxt = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        productimgtxt = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        productquantitytxt = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        addproductbtn = new javax.swing.JButton();
        productshorttxt = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        img1txt = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        img2txt = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        img3txt = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        product_statustxt = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1280, 660));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(153, 0, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(199, 226, 255));
        jLabel1.setText("Product Mini Image");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 330, -1, -1));

        productpricetxt.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        productpricetxt.setForeground(new java.awt.Color(255, 255, 255));
        productpricetxt.setBorder(null);
        jPanel1.add(productpricetxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 270, 300, 40));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(199, 226, 255));
        jLabel2.setText("Product ID");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, -1, -1));

        jLabel3.setForeground(new java.awt.Color(102, 255, 255));
        jLabel3.setText("___________________________________________");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 290, -1, -1));

        productidtxt.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        productidtxt.setForeground(new java.awt.Color(255, 255, 255));
        productidtxt.setBorder(null);
        jPanel1.add(productidtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, 300, 40));

        jLabel4.setForeground(new java.awt.Color(102, 255, 255));
        jLabel4.setText("___________________________________________");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 310, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(199, 226, 255));
        jLabel5.setText("Product Name");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, -1, -1));

        productnametxt.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        productnametxt.setForeground(new java.awt.Color(255, 255, 255));
        productnametxt.setBorder(null);
        jPanel1.add(productnametxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, 300, 40));

        jLabel6.setForeground(new java.awt.Color(102, 255, 255));
        jLabel6.setText("___________________________________________");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(199, 226, 255));
        jLabel7.setText("Product Category");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, -1, -1));

        productcategorytxt.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        productcategorytxt.setForeground(new java.awt.Color(255, 255, 255));
        productcategorytxt.setBorder(null);
        jPanel1.add(productcategorytxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, 300, 40));

        jLabel8.setForeground(new java.awt.Color(102, 255, 255));
        jLabel8.setText("___________________________________________");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 310, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(199, 226, 255));
        jLabel9.setText("Product Quantity");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 340, -1, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(199, 226, 255));
        jLabel10.setText("Product Short Description");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 100, -1, -1));

        productimgtxt.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        productimgtxt.setForeground(new java.awt.Color(255, 255, 255));
        productimgtxt.setBorder(null);
        jPanel1.add(productimgtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 360, 300, 40));

        jLabel11.setForeground(new java.awt.Color(102, 255, 255));
        jLabel11.setText("___________________________________________");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 380, -1, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(199, 226, 255));
        jLabel12.setText("Product Price");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 240, -1, -1));

        productquantitytxt.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        productquantitytxt.setForeground(new java.awt.Color(255, 255, 255));
        productquantitytxt.setBorder(null);
        jPanel1.add(productquantitytxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 370, 300, 40));

        jLabel13.setForeground(new java.awt.Color(102, 255, 255));
        jLabel13.setText("___________________________________________");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 390, -1, -1));

        addproductbtn.setBackground(new java.awt.Color(199, 226, 255));
        addproductbtn.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        addproductbtn.setForeground(new java.awt.Color(25, 118, 221));
        addproductbtn.setText("ADD PRODUCT");
        addproductbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addproductbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addproductbtnMouseClicked(evt);
            }
        });
        addproductbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addproductbtnActionPerformed(evt);
            }
        });
        jPanel1.add(addproductbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 480, 460, 50));

        productshorttxt.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        productshorttxt.setForeground(new java.awt.Color(255, 255, 255));
        productshorttxt.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        productshorttxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel1.add(productshorttxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 130, 300, 100));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(199, 226, 255));
        jLabel15.setText("Product Full Image 1");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 100, -1, -1));

        img1txt.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        img1txt.setForeground(new java.awt.Color(255, 255, 255));
        img1txt.setBorder(null);
        jPanel1.add(img1txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 130, 330, 40));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(199, 226, 255));
        jLabel16.setText("Product Full Image 2");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 180, -1, -1));

        img2txt.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        img2txt.setForeground(new java.awt.Color(255, 255, 255));
        img2txt.setBorder(null);
        jPanel1.add(img2txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 210, 330, 40));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(199, 226, 255));
        jLabel17.setText("Product Full Image 3");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 260, -1, -1));

        img3txt.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        img3txt.setForeground(new java.awt.Color(255, 255, 255));
        img3txt.setBorder(null);
        jPanel1.add(img3txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 290, 330, 40));

        jLabel14.setForeground(new java.awt.Color(102, 255, 255));
        jLabel14.setText("_______________________________________________________________");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 155, 330, -1));

        jLabel18.setForeground(new java.awt.Color(102, 255, 255));
        jLabel18.setText("_________________________________________________________________");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 233, 330, -1));

        jLabel19.setForeground(new java.awt.Color(102, 255, 255));
        jLabel19.setText("_______________________________________________________________");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 315, 330, -1));

        jLabel20.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(199, 226, 255));
        jLabel20.setText("Product Status");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 340, 190, -1));

        product_statustxt.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        product_statustxt.setForeground(new java.awt.Color(255, 255, 255));
        product_statustxt.setBorder(null);
        jPanel1.add(product_statustxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 370, 330, 40));

        jLabel21.setForeground(new java.awt.Color(102, 255, 255));
        jLabel21.setText("_______________________________________________________________");
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 395, 330, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 1290, 660));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addproductbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addproductbtnMouseClicked
        // TODO add your handling code here:
         dbcon c=new dbcon();
         String product_id=productidtxt.getText();
          String product_name=productnametxt.getText();
           String product_category=productcategorytxt.getText();
            String product_quantity=productquantitytxt.getText();
             String product_shortdesc=productshorttxt.getText();
              String product_price=productpricetxt.getText();
               String product_img=productimgtxt.getText();
               String product_img1=img1txt.getText();
               String product_img2=img2txt.getText();
               String product_img3=img3txt.getText();
               String product_status=product_statustxt.getText();
               
               
               
        
        if (product_id.equals("")) {
      
            JOptionPane.showMessageDialog(null, "Enter product ID");
            return;
        }
          if (product_name.equals("")) {
      
            JOptionPane.showMessageDialog(null, "Enter product Name");
            return;
        }
            if (product_category.equals("")) {
      
            JOptionPane.showMessageDialog(null, "Enter product Category");
            return;
        }
          if (product_quantity.equals("")) {
      
            JOptionPane.showMessageDialog(null, "Enter product Quantity");
            return;
        }
            if (product_shortdesc.equals("")) {
      
            JOptionPane.showMessageDialog(null, "Enter product Short Description");
            return;
        }
              if (product_price.equals("")) {
      
            JOptionPane.showMessageDialog(null, "Enter product Price");
            return;
        }
               if (product_img.equals("")) {

            JOptionPane.showMessageDialog(null, "Enter product Image");
            return;
        }
                if (product_img1.equals("")) {

            JOptionPane.showMessageDialog(null, "Enter product Image 1");
            return;
        }
                 if (product_img2.equals("")) {

            JOptionPane.showMessageDialog(null, "Enter product Image2");
            return;
        }
                  if (product_img3.equals("")) {

            JOptionPane.showMessageDialog(null, "Enter product Image3");
            return;
        }
                  if (product_status.equals("")) {

            JOptionPane.showMessageDialog(null, "Enter product status");
            return;
        }
                  
                String addQuery="INSERT INTO `product` (`id`, `product_name`, `price`, `quantity`, `status`, `category`, `picture`, `shortinfo`, `bigpic1`, `bigpic2`, `bigpic3`) VALUES ('"+product_id+"', '"+product_name+"', '"+product_price+"', '"+product_quantity+"','"+product_status+"', '"+product_category+"', '"+product_img+"', '"+product_shortdesc+"','"+product_img1+"','"+product_img2+"','"+product_img3+"');";
        try {
            c.s.executeUpdate(addQuery);
            JOptionPane.showMessageDialog(null, "Prodcut Added Successfully");
           
        } catch (SQLException ex) {
            Logger.getLogger(signup.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_addproductbtnMouseClicked

    private void addproductbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addproductbtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addproductbtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addproductbtn;
    private javax.swing.JTextField img1txt;
    private javax.swing.JTextField img2txt;
    private javax.swing.JTextField img3txt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField product_statustxt;
    private javax.swing.JTextField productcategorytxt;
    private javax.swing.JTextField productidtxt;
    private javax.swing.JTextField productimgtxt;
    private javax.swing.JTextField productnametxt;
    private javax.swing.JTextField productpricetxt;
    private javax.swing.JTextField productquantitytxt;
    private javax.swing.JTextField productshorttxt;
    // End of variables declaration//GEN-END:variables
}
