package activity;

import Database.dbcon;
import com.mysql.cj.protocol.Resultset;
import java.awt.Color;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author User
 */
public class signup extends javax.swing.JFrame {

  
    public signup() {
        initComponents();
        
        
        phonetxt.setBackground(new Color(0,0,0,1));
        nametxt.setBackground(new Color(0,0,0,1));
        emailtxt.setBackground(new Color(0,0,0,1));
        passwordtxt.setBackground(new Color(0,0,0,1));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        phonetxt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        nametxt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        emailtxt = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        femalecheckbox = new javax.swing.JCheckBox();
        malecheckbox = new javax.swing.JCheckBox();
        jLabel8 = new javax.swing.JLabel();
        passwordtxt = new javax.swing.JPasswordField();
        jLabel9 = new javax.swing.JLabel();
        signupbutton = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1130, 580));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(25, 118, 221));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(199, 226, 255));
        jLabel1.setText("Password");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 320, 340, -1));

        jLabel2.setForeground(new java.awt.Color(51, 255, 255));
        jLabel2.setText("____________________________________________________");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 375, 370, -1));

        phonetxt.setFont(phonetxt.getFont().deriveFont(phonetxt.getFont().getSize()+3f));
        phonetxt.setForeground(new java.awt.Color(255, 255, 255));
        phonetxt.setBorder(null);
        jPanel1.add(phonetxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 240, 370, 40));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(199, 226, 255));
        jLabel3.setText("Full Name");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, 340, -1));

        nametxt.setFont(nametxt.getFont().deriveFont(nametxt.getFont().getSize()+3f));
        nametxt.setForeground(new java.awt.Color(255, 255, 255));
        nametxt.setBorder(null);
        jPanel1.add(nametxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 95, 370, 40));

        jLabel4.setForeground(new java.awt.Color(51, 255, 255));
        jLabel4.setText("____________________________________________________");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 120, 400, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(199, 226, 255));
        jLabel5.setText("Email");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, 340, -1));

        emailtxt.setFont(emailtxt.getFont().deriveFont(emailtxt.getFont().getSize()+3f));
        emailtxt.setForeground(new java.awt.Color(255, 255, 255));
        emailtxt.setBorder(null);
        jPanel1.add(emailtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, 370, 40));

        jLabel6.setForeground(new java.awt.Color(51, 255, 255));
        jLabel6.setText("____________________________________________________");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 195, 370, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(199, 226, 255));
        jLabel7.setText("Gender");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 290, 60, -1));

        buttonGroup1.add(femalecheckbox);
        femalecheckbox.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        femalecheckbox.setForeground(new java.awt.Color(255, 255, 255));
        femalecheckbox.setText("Female");
        femalecheckbox.setBorder(null);
        jPanel1.add(femalecheckbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 290, -1, -1));

        buttonGroup1.add(malecheckbox);
        malecheckbox.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        malecheckbox.setForeground(new java.awt.Color(255, 255, 255));
        malecheckbox.setText("Male");
        malecheckbox.setBorder(null);
        malecheckbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                malecheckboxActionPerformed(evt);
            }
        });
        jPanel1.add(malecheckbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 290, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(199, 226, 255));
        jLabel8.setText("Phone Number");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 212, 340, -1));

        passwordtxt.setFont(new java.awt.Font("sansserif", 0, 15)); // NOI18N
        passwordtxt.setForeground(new java.awt.Color(255, 255, 255));
        passwordtxt.setBorder(null);
        jPanel1.add(passwordtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 350, 370, 40));

        jLabel9.setForeground(new java.awt.Color(51, 255, 255));
        jLabel9.setText("____________________________________________________");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 265, 370, -1));

        signupbutton.setBackground(new java.awt.Color(199, 226, 255));
        signupbutton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        signupbutton.setForeground(new java.awt.Color(25, 118, 221));
        signupbutton.setText("SIGN UP");
        signupbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signupbuttonActionPerformed(evt);
            }
        });
        jPanel1.add(signupbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 410, 370, 40));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Login");
        jLabel10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 530, 50, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Already have an account?");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 530, 220, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 0, 590, 580));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photos/signup backgroud.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 544, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 580, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, 580));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
      login l=new login();
      l.setVisible(true);
       
      dispose();
        
      
    }//GEN-LAST:event_jLabel10MouseClicked

    private void signupbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signupbuttonActionPerformed
        dbcon c=new dbcon();
         String gender;
        String name=nametxt.getText();
       String email=emailtxt.getText();
       String phone=phonetxt.getText();
       String password=passwordtxt.getText();
        if (malecheckbox.isSelected()) {
            gender="male";
        }else if (femalecheckbox.isSelected()) {
            gender="female";
        }else{
            JOptionPane.showMessageDialog(null, "Please select a gender.");
                    return;
        }
        if (name.equals("")) {
            JOptionPane.showMessageDialog(null, "Enter Your Name");
            return;
        }
        
        if (email.equals("")) {
            JOptionPane.showMessageDialog(null, "Enter Your Email Address");
            return;
        }
        if (phone.equals("")) {
            JOptionPane.showMessageDialog(null, "Enter Your Phone Number");
            return;
        }
        if (password.equals("")) {
            JOptionPane.showMessageDialog(null, "Enter Your Password");
            return;
        }
        
        String sigupQuery="INSERT INTO `signup` (`name`, `email`, `number`, `gender`, `password`) VALUES ('"+name+"', '"+email+"', '"+phone+"', '"+gender+"', '"+password+"');";
        try {
             c.s.executeUpdate(sigupQuery);
            JOptionPane.showMessageDialog(null, "Registration Successfully");
             MainActivity mainActivity=new MainActivity(name, phone, gender, email);
                mainActivity.setVisible(true);
                dispose();
        } catch (SQLException ex) {
            Logger.getLogger(signup.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_signupbuttonActionPerformed

    private void malecheckboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_malecheckboxActionPerformed
                 
    }//GEN-LAST:event_malecheckboxActionPerformed

   
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
              new signup().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField emailtxt;
    private javax.swing.JCheckBox femalecheckbox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JCheckBox malecheckbox;
    private javax.swing.JTextField nametxt;
    private javax.swing.JPasswordField passwordtxt;
    private javax.swing.JTextField phonetxt;
    private javax.swing.JButton signupbutton;
    // End of variables declaration//GEN-END:variables
}
